name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      env:
        SECRET_VARIABLE: ${{ secrets.SECRET_VARIABLE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    - name: Deploy
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/tamacat -Dtoken=${GITHUB_TOKEN}
